import HeroBanner from "@/components/HeroBanner";
import ProductCard from "@/components/ProductCard";
import Wrapper from "@/components/Wrapper";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Online shoes store | Next JS and Tailwind CSS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                    rel="stylesheet"
                />
            </Head>

            <main>
                <HeroBanner />
                <Wrapper>
                    {/* heading and paragaph start */}
                    <div className="text-center max-w-[800px] mx-auto my-[50px] md:my-[80px]">
                        <div className="text-[28px] md:text-[34px] mb-5 font-semibold leading-tight">
                            Cushioning for Your Miles
                        </div>
                        <div className="text-md md:text-xl">
                            A lightweight Nike ZoomX midsole is combined with increased stack
                            heights to help provide cushioning during extended stretches of running.
                        </div>
                    </div>
                    {/* heading and paragaph end */}

                    {/* products grid start */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 my-14 px-5 md:px-0">
                        <ProductCard />
                        <ProductCard />
                        <ProductCard />
                        <ProductCard />
                        <ProductCard />
                        <ProductCard />
                        <ProductCard />
                        <ProductCard />
                        <ProductCard />
                    </div>
                    {/* products grid end */}
                </Wrapper>
            </main>
        </>
    );
}
